async function getOrCreateCategoria(Categoria, nombre) {
  let categoria = await Categoria.findOne({ where: { nombre } });
  if (!categoria) {
    categoria = await Categoria.create({ nombre });
  }
  return categoria;
}

async function getOrCreateUsuario(Usuario, userData) {
  const usuario = await Usuario.findOne({ where: { email: userData.email } });
  if (!usuario) {
    await Usuario.create(userData);
  }
}

async function getOrCreateProducto(Producto, productoData) {
  const existente = await Producto.findOne({ where: { nombre: productoData.nombre } });
  if (!existente) {
    await Producto.create(productoData);
  }
}

function makeImageUrl(nombre) {
  return `https://via.placeholder.com/600x400?text=${encodeURIComponent(nombre)}`;
}

async function seedDatabase({ Categoria, Producto, Usuario }) {
  await getOrCreateUsuario(Usuario, {
    nombre: 'Admin',
    email: 'admin@gmail.com',
    password: '123456',
    role: 'admin',
  });

  await getOrCreateUsuario(Usuario, {
    nombre: 'Cliente',
    email: 'cliente@gmail.com',
    password: '123456',
    role: 'client',
  });

  const categoryNames = {
    calefaccion: 'Calefacción',
    cocina: 'Cocina',
    computacion: 'Computación',
    celulares: 'Celulares',
    audio: 'Audio',
    gaming: 'Gaming',
    hogar: 'Hogar',
    oficina: 'Oficina',
    televisores: 'Televisores',
    herramientas: 'Herramientas',
  };

  const categorias = {};
  for (const [key, nombre] of Object.entries(categoryNames)) {
    categorias[key] = await getOrCreateCategoria(Categoria, nombre);
  }

  const productos = [
    {
      nombre: 'Calefón Orbis 14L Gas Natural',
      precio: 245000,
      stock: 12,
      descuento: true,
      porcentajeDescuento: 10,
      visible: true,
      image: makeImageUrl('Calefón Orbis 14L Gas Natural'),
      id_categoria: categorias.calefaccion.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Calefón Longvie 12L Multigas',
      precio: 198500,
      stock: 8,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Calefón Longvie 12L Multigas'),
      id_categoria: categorias.calefaccion.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Calefón Rheem 16L Tiro Natural',
      precio: 312000,
      stock: 5,
      descuento: true,
      porcentajeDescuento: 15,
      visible: true,
      image: makeImageUrl('Calefón Rheem 16L Tiro Natural'),
      id_categoria: categorias.calefaccion.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Calefactor Eskabe S21',
      precio: 176000,
      stock: 14,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Calefactor Eskabe S21'),
      id_categoria: categorias.calefaccion.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Estufa a Gas Emege 5000',
      precio: 99000,
      stock: 9,
      descuento: true,
      porcentajeDescuento: 12,
      visible: true,
      image: makeImageUrl('Estufa a Gas Emege 5000'),
      id_categoria: categorias.calefaccion.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Microondas BGH Quick Chef',
      precio: 185000,
      stock: 7,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Microondas BGH Quick Chef'),
      id_categoria: categorias.cocina.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Pava Eléctrica Philips',
      precio: 72000,
      stock: 20,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Pava Eléctrica Philips'),
      id_categoria: categorias.cocina.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Batidora Planetaria Liliana',
      precio: 138000,
      stock: 11,
      descuento: true,
      porcentajeDescuento: 8,
      visible: true,
      image: makeImageUrl('Batidora Planetaria Liliana'),
      id_categoria: categorias.cocina.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Licuadora Oster Xpert',
      precio: 95000,
      stock: 6,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Licuadora Oster Xpert'),
      id_categoria: categorias.cocina.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Horno Electrico Smartlife 45L',
      precio: 167500,
      stock: 4,
      descuento: true,
      porcentajeDescuento: 18,
      visible: true,
      image: makeImageUrl('Horno Electrico Smartlife 45L'),
      id_categoria: categorias.cocina.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Notebook Lenovo IdeaPad 1',
      precio: 589999,
      stock: 15,
      descuento: true,
      porcentajeDescuento: 5,
      visible: true,
      image: makeImageUrl('Notebook Lenovo IdeaPad 1'),
      id_categoria: categorias.computacion.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Notebook HP 15s',
      precio: 679999,
      stock: 10,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Notebook HP 15s'),
      id_categoria: categorias.computacion.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Monitor LG 24 Full HD',
      precio: 219999,
      stock: 18,
      descuento: true,
      porcentajeDescuento: 7,
      visible: true,
      image: makeImageUrl('Monitor LG 24 Full HD'),
      id_categoria: categorias.computacion.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Teclado Logitech K120',
      precio: 18999,
      stock: 40,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Teclado Logitech K120'),
      id_categoria: categorias.computacion.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Mouse Inalambrico Microsoft',
      precio: 14999,
      stock: 32,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Mouse Inalambrico Microsoft'),
      id_categoria: categorias.computacion.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Smartphone Samsung Galaxy A16',
      precio: 257699,
      stock: 22,
      descuento: true,
      porcentajeDescuento: 6,
      visible: true,
      image: makeImageUrl('Smartphone Samsung Galaxy A16'),
      id_categoria: categorias.celulares.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Smartphone Motorola G84',
      precio: 299999,
      stock: 13,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Smartphone Motorola G84'),
      id_categoria: categorias.celulares.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Smartphone Xiaomi Redmi Note 13',
      precio: 284999,
      stock: 19,
      descuento: true,
      porcentajeDescuento: 9,
      visible: true,
      image: makeImageUrl('Smartphone Xiaomi Redmi Note 13'),
      id_categoria: categorias.celulares.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Auriculares Bluetooth JBL Tune 520',
      precio: 89999,
      stock: 28,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Auriculares Bluetooth JBL Tune 520'),
      id_categoria: categorias.celulares.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Power Bank 20000 mAh Anker',
      precio: 49999,
      stock: 17,
      descuento: true,
      porcentajeDescuento: 11,
      visible: true,
      image: makeImageUrl('Power Bank 20000 mAh Anker'),
      id_categoria: categorias.celulares.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Parlante Bluetooth Sony SRS-XB13',
      precio: 74999,
      stock: 16,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Parlante Bluetooth Sony SRS-XB13'),
      id_categoria: categorias.audio.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Auriculares JBL Quantum 100',
      precio: 52999,
      stock: 24,
      descuento: true,
      porcentajeDescuento: 8,
      visible: true,
      image: makeImageUrl('Auriculares JBL Quantum 100'),
      id_categoria: categorias.audio.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Soundbar Samsung 2.1',
      precio: 199999,
      stock: 8,
      descuento: true,
      porcentajeDescuento: 14,
      visible: true,
      image: makeImageUrl('Soundbar Samsung 2.1'),
      id_categoria: categorias.audio.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Microfono USB HyperX QuadCast S',
      precio: 149999,
      stock: 9,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Microfono USB HyperX QuadCast S'),
      id_categoria: categorias.audio.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Tocadiscos Audio-Technica LP60X',
      precio: 239999,
      stock: 5,
      descuento: true,
      porcentajeDescuento: 12,
      visible: true,
      image: makeImageUrl('Tocadiscos Audio-Technica LP60X'),
      id_categoria: categorias.audio.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Consola PlayStation 5 Slim',
      precio: 999999,
      stock: 6,
      descuento: true,
      porcentajeDescuento: 4,
      visible: true,
      image: makeImageUrl('Consola PlayStation 5 Slim'),
      id_categoria: categorias.gaming.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Consola Xbox Series S',
      precio: 499999,
      stock: 11,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Consola Xbox Series S'),
      id_categoria: categorias.gaming.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Volante Logitech G29',
      precio: 399999,
      stock: 7,
      descuento: true,
      porcentajeDescuento: 13,
      visible: true,
      image: makeImageUrl('Volante Logitech G29'),
      id_categoria: categorias.gaming.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Silla Gamer Corsair TC100',
      precio: 329999,
      stock: 14,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Silla Gamer Corsair TC100'),
      id_categoria: categorias.gaming.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Mouse Gamer Redragon M711',
      precio: 24999,
      stock: 26,
      descuento: true,
      porcentajeDescuento: 10,
      visible: true,
      image: makeImageUrl('Mouse Gamer Redragon M711'),
      id_categoria: categorias.gaming.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Aspiradora Samsung 1400W',
      precio: 159999,
      stock: 13,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Aspiradora Samsung 1400W'),
      id_categoria: categorias.hogar.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Plancha a Vapor Black+Decker',
      precio: 45999,
      stock: 18,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Plancha a Vapor Black+Decker'),
      id_categoria: categorias.hogar.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Ventilador de Pie Liliana 16"',
      precio: 69999,
      stock: 10,
      descuento: true,
      porcentajeDescuento: 7,
      visible: true,
      image: makeImageUrl('Ventilador de Pie Liliana 16'),
      id_categoria: categorias.hogar.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Juego de Sabanas Cannon Queen',
      precio: 54999,
      stock: 21,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Juego de Sabanas Cannon Queen'),
      id_categoria: categorias.hogar.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Set Organizador de Cocina',
      precio: 22999,
      stock: 35,
      descuento: true,
      porcentajeDescuento: 15,
      visible: true,
      image: makeImageUrl('Set Organizador de Cocina'),
      id_categoria: categorias.hogar.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Notebook Stand Ajustable',
      precio: 34999,
      stock: 30,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Notebook Stand Ajustable'),
      id_categoria: categorias.oficina.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Impresora Epson EcoTank L3250',
      precio: 289999,
      stock: 12,
      descuento: true,
      porcentajeDescuento: 6,
      visible: true,
      image: makeImageUrl('Impresora Epson EcoTank L3250'),
      id_categoria: categorias.oficina.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Silla de Oficina Ergonómica',
      precio: 189999,
      stock: 9,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Silla de Oficina Ergonomica'),
      id_categoria: categorias.oficina.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Archivador Metálico 3 Cajones',
      precio: 129999,
      stock: 8,
      descuento: true,
      porcentajeDescuento: 9,
      visible: true,
      image: makeImageUrl('Archivador Metalico 3 Cajones'),
      id_categoria: categorias.oficina.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Lampara LED de Escritorio',
      precio: 19999,
      stock: 44,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Lampara LED de Escritorio'),
      id_categoria: categorias.oficina.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Smart TV LG 50 4K',
      precio: 799999,
      stock: 5,
      descuento: true,
      porcentajeDescuento: 10,
      visible: true,
      image: makeImageUrl('Smart TV LG 50 4K'),
      id_categoria: categorias.televisores.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Smart TV Samsung 43 Crystal',
      precio: 599999,
      stock: 12,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Smart TV Samsung 43 Crystal'),
      id_categoria: categorias.televisores.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Android TV Noblex 32',
      precio: 289999,
      stock: 16,
      descuento: true,
      porcentajeDescuento: 5,
      visible: true,
      image: makeImageUrl('Android TV Noblex 32'),
      id_categoria: categorias.televisores.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Soporte TV Movil 32 a 70',
      precio: 39999,
      stock: 19,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Soporte TV Movil 32 a 70'),
      id_categoria: categorias.televisores.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Chromecast Google TV',
      precio: 64999,
      stock: 27,
      descuento: true,
      porcentajeDescuento: 11,
      visible: true,
      image: makeImageUrl('Chromecast Google TV'),
      id_categoria: categorias.televisores.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Taladro Percutor Bosch',
      precio: 149999,
      stock: 15,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Taladro Percutor Bosch'),
      id_categoria: categorias.herramientas.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Amoladora Black+Decker 900W',
      precio: 87999,
      stock: 10,
      descuento: true,
      porcentajeDescuento: 8,
      visible: true,
      image: makeImageUrl('Amoladora Black+Decker 900W'),
      id_categoria: categorias.herramientas.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Juego de Llaves Stillson',
      precio: 54999,
      stock: 23,
      descuento: false,
      porcentajeDescuento: 0,
      visible: true,
      image: makeImageUrl('Juego de Llaves Stillson'),
      id_categoria: categorias.herramientas.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Caja de Herramientas Tramontina',
      precio: 39999,
      stock: 13,
      descuento: true,
      porcentajeDescuento: 6,
      visible: true,
      image: makeImageUrl('Caja de Herramientas Tramontina'),
      id_categoria: categorias.herramientas.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
    {
      nombre: 'Soldadora Inverter Lusqtoff',
      precio: 219999,
      stock: 4,
      descuento: true,
      porcentajeDescuento: 16,
      visible: true,
      image: makeImageUrl('Soldadora Inverter Lusqtoff'),
      id_categoria: categorias.herramientas.id_categoria,
      validoDesde: '2024-01-01',
      validoHasta: '2099-12-31',
    },
  ];

  for (const producto of productos) {
    await getOrCreateProducto(Producto, producto);
  }
}

export default seedDatabase;
